<?php
return array (
  'db_type' => 'mysql',
  'db_host' => '103.231.15.42',
  'db_name' => 'shuangvod',
  'db_user' => 'myuser',
  'db_pwd' => 'lhl850503',
  'db_port' => '3306',
  'db_prefix' => 'sv_',
  'db_charset' => 'utf8',
  'default_theme' => 'meiju',
  'site_name' => '双视影院',
  'site_path' => '/',
  'site_url' => 'http://www.shuangvod.com/',
  'site_icp' => 'ICP备2010111号',
  'site_email' => '17043578@qq.com',
  'site_keywords' => '电影天堂，迅雷电影下载，双视影院',
  'site_description' => '双视影院为您提供电影天堂最新电影迅雷下载，每日第一时间更新最新电影电视剧等视频资源保证您的下载观看体验。',
  'site_hot' => '',
  'site_tongji' => '<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?7d1efa9e6250268189e47f3e68cc6e59";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

<script src="https://s6.cnzz.com/z_stat.php?id=5042486&web_id=5042486" language="JavaScript"></script>',
  'site_copyright' => '',
  'admin_order_type' => 'addtime',
  'admin_time_edit' => true,
  'admin_ads_file' => 'Runtime/js',
  'url_num_admin' => '18',
  'home_pagenum' => '3',
  'url_html' => '0',
  'html_file_suffix' => '.html',
  'url_html_list' => '1',
  'url_vodlist' => '{listdir}/index.html',
  'url_newslist' => '{listdir}/index.html',
  'url_voddata' => '{listdir}/{pinyin}/index.html',
  'url_newsdata' => '{listdir}/{id}/index.html',
  'url_html_play' => '0',
  'url_play' => '{listdir}/{id}/play.html',
  'url_special' => 'detail/',
  'url_map' => 'detail/',
  'url_mytpl' => 'detail/',
  'url_time' => '2',
  'url_number' => '20',
  'url_rewrite' => '1',
  'url_html_suffix' => '.html',
  'rewrite_vodlist' => '/vod-show-id-$id-p-$page',
  'rewrite_voddetail' => '/vod-read-id-$id',
  'rewrite_vodplay' => '/vodplay-$id-$sid-$pid',
  'rewrite_vodsearch' => '/vod-search-wd-$wd$actor$director-p-$page',
  'rewrite_vodtype' => '/vod-type-id-$id-wd-$wd-mcid-$mcid-letter-$letter-year-$year-area-$area-lz-$lz-order-$order-p-$page',
  'rewrite_vodtag' => '/tag-vod-wd-$wd-p-$page',
  'rewrite_newslist' => '/news-show-id-$id-p-$page',
  'rewrite_newsdetail' => '/news-read-id-$id',
  'rewrite_newssearch' => '/news-search-wd-$wd-p-$page',
  'rewrite_newstag' => '/tag-news-wd-$wd-p-$page',
  'rewrite_speciallist' => '/special-show-p-$page',
  'rewrite_specialdetail' => '/special-read-id-$id',
  'rewrite_guestbook' => '/gb-show-p-$page',
  'rewrite_map' => '/map-show-id-$id-limit-$limit',
  'rewrite_mytpl' => '/my-show-id-$id',
  'data_cache_type' => 'file',
  'data_cache_vod' => '0',
  'data_cache_news' => '0',
  'data_cache_special' => '0',
  'data_cache_vodforeach' => '0',
  'data_cache_newsforeach' => '0',
  'data_cache_specialforeach' => '0',
  'tmpl_cache_on' => false,
  'html_cache_on' => false,
  'html_cache_index' => '1',
  'html_cache_list' => '1.5',
  'html_cache_content' => '12',
  'html_cache_play' => '12',
  'html_cache_ajax' => '12',
  'html_cache_time' => 0,
  'html_cache_rules' => 
  array (
    'index:index' => 
    array (
      0 => '{:action}',
      1 => 3600,
    ),
    'vod:show' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 5400,
    ),
    'news:show' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 5400,
    ),
    'vod:read' => 
    array (
      0 => '{:module}_{:action}/{id|md5}',
      1 => 43200,
    ),
    'news:read' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 43200,
    ),
    'vod:play' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 43200,
    ),
    'my:show' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 43200,
    ),
  ),
  'upload_path' => 'Uploads',
  'upload_style' => 'Y-m-d',
  'upload_class' => 'jpg,gif,png,jpeg',
  'upload_http_down' => '30',
  'upload_http' => false,
  'upload_thumb' => true,
  'upload_thumb_w' => '120',
  'upload_thumb_h' => '140',
  'upload_water' => false,
  'upload_water_pct' => '75',
  'upload_water_pos' => '2',
  'upload_water_img' => './Public/images/water.gif',
  'upload_ftp' => false,
  'upload_ftp_del' => '0',
  'upload_ftp_host' => '',
  'upload_ftp_user' => '',
  'upload_ftp_pass' => '',
  'upload_ftp_port' => '',
  'upload_ftp_dir' => '/',
  'upload_http_prefix' => '',
  'play_width' => '700',
  'play_height' => '480',
  'play_show' => '0',
  'play_second' => 10,
  'play_area' => '大陆,香港,台湾,美国,韩国,日本,泰国,新加坡,马来西亚,印度,英国,法国,加拿大,西班牙,俄罗斯,其它',
  'play_year' => '2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000,1990,1980,1970,1960,1950',
  'play_language' => '国语,英语,粤语,闽南语,韩语,日语,国语/粤语,其它',
  'play_playad' => 'http://api.muyu.cc/loading.html',
  'play_qvod' => 'http://u.daicuo.com/install/down.php?id=qvod',
  'play_bdhd' => 'http://u.daicuo.com/install/down.php?id=bdhd',
  'play_server' => 
  array (
    'down_a' => 'http://downa.feifeicms.cc/',
    'down_b' => 'http://downb.feifeicms.cc/',
  ),
  'play_collect' => true,
  'rand_tag' => '0',
  'play_collect_name' => '0',
  'play_collect_time' => '2',
  'rand_hits' => '9',
  'rand_updown' => '9',
  'rand_gold' => '9',
  'rand_golder' => '9',
  'user_vcode' => '1',
  'user_check' => '0',
  'user_second' => '0',
  'user_gbnum' => '10',
  'user_cmnum' => '10',
  'user_replace' => '她妈|它妈|他妈|你妈|去死|贱人',
  'play_collect_content' => 
  array (
    0 => '',
  ),
  'user_gbcm' => false,
  'data_cache_foreach' => '5641f855bc7a7',
  'html_home_suffix' => '.html',
);
?>